"use client"

import type * as React from "react"
import { Download } from "lucide-react"
import { cn } from "@/lib/utils"

function Card({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card"
      className={cn("bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm", className)}
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-header"
      className={cn(
        "@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6",
        className,
      )}
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return <div data-slot="card-title" className={cn("leading-none font-semibold", className)} {...props} />
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return <div data-slot="card-description" className={cn("text-muted-foreground text-sm", className)} {...props} />
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-action"
      className={cn("col-start-2 row-span-2 row-start-1 self-start justify-self-end", className)}
      {...props}
    />
  )
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  const handleDownloadReport = () => {
    const reportContent = `
ENERGY EFFICIENCY ASSESSMENT REPORT
Generated on: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
This report provides a comprehensive analysis of energy efficiency metrics
and recommendations for improvement.

ASSESSMENT RESULTS
- Current Energy Rating: B+
- Potential Savings: 15-20%
- Recommended Actions: Insulation upgrade, HVAC optimization
- Estimated ROI: 3-5 years

DETAILED FINDINGS
1. Building Envelope Performance
2. HVAC System Efficiency
3. Lighting and Electrical Systems
4. Renewable Energy Potential

RECOMMENDATIONS
- Priority 1: Upgrade insulation
- Priority 2: Install smart thermostats
- Priority 3: LED lighting conversion

Report generated by Property Insights Tool
    `

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "Energy-Efficiency-Assessment-Report.txt"
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div data-slot="card-content" className={cn("px-6", className)} {...props}>
      {props.children}
      <button
        onClick={handleDownloadReport}
        className="mt-4 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
      >
        <Download className="h-4 w-4" />
        Download Energy Efficiency Assessment Report
      </button>
    </div>
  )
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return <div data-slot="card-footer" className={cn("flex items-center px-6 [.border-t]:pt-6", className)} {...props} />
}

export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent }
