-- Insert the property data with corrected values
INSERT INTO properties (
  property_id,
  matterport_tour_id,
  address,
  estimated_price,
  low_price,
  high_price,
  last_sale_price,
  property_valuation,
  total_area,
  floor_area,
  land_area,
  bed_area,
  master_bed_area,
  bath_area,
  bedrooms,
  bathrooms,
  car_spaces,
  build_year,
  property_type,
  views,
  avg_daily_views,
  avg_session_time,
  engaged_inspections,
  engaged_visitors,
  panorama_count,
  ceiling_height,
  floors,
  hallway_avg_width,
  hardwood_area,
  tile_area,
  carpet_area,
  air_conditioning_count,
  air_conditioning_type,
  smoke_alarm_count,
  ceiling_light_count,
  door_count,
  fireplace,
  primary_ceiling_type,
  primary_wall_type,
  primary_flooring_type,
  primary_internal_color,
  damage_walls,
  damage_floor,
  damage_ceiling,
  damage_known,
  overall_condition,
  street_no,
  street_name,
  street_type,
  locality,
  state,
  postcode,
  latitude,
  longitude,
  gnaf_id,
  meshblock,
  meshblock_2016,
  sa1_id,
  sa2_id,
  climate_zone,
  upload_time,
  scanned_date,
  scan_purpose,
  rescan_or_original,
  multiple_scans,
  unique_features,
  property_description
) VALUES (
  '25763',
  'ZUCRWEgFkxk',
  '3 Bellavista Terrace, PADDINGTON QLD 4064',
  1340589,
  1152907,
  1528271,
  375000,
  470000,
  142.63,
  115,
  255,
  17.67,
  9.17,
  13.32,
  3,
  2,
  1,
  'Unknown',
  'HOUSE',
  55,
  1.49,
  132.88,
  51,
  51,
  73,
  2.42,
  2,
  3.28,
  48.99,
  35.83,
  38.90,
  3,
  'Fujitsu Inverter Split System',
  5,
  15,
  20,
  'No',
  'flat',
  'plaster',
  'hardwood',
  '#d2d0ca',
  'No',
  'No',
  'No',
  'No',
  'Property shows no notable visible damage on any surface',
  '3',
  'Bellavista',
  'Terrace',
  'PADDINGTON',
  'QLD',
  '4064',
  -27.455381,
  152.988639,
  'GAQLD155682091',
  'MB2130563208900',
  'MB1630563208900',
  30504113517,
  305041135,
  'Zone 2',
  '2025-06-24 00:12:52.377000 UTC',
  '2025-07-24 09:30:00.000000 UTC',
  'Residential',
  'No',
  '1- Carport',
  'Exceptionally Wide Hallway: The property features a hallway with an average width of approximately 3.28 meters, creating an unusually spacious central corridor that enhances the sense of openness.',
  'This contemporary two-storey home is defined by a uniquely spacious layout and a seamless connection between its indoor and outdoor living areas.'
) ON CONFLICT (property_id) DO UPDATE SET
  smoke_alarm_count = 5,
  postcode = '4064',
  climate_zone = 'Zone 2',
  scan_purpose = 'Residential',
  updated_at = NOW();
